const renameJobs = {
  48: {
    subject: "Theory of Computation",

    titles: [
      "Decidability 03 : Miscellaneous Topic  || (NO DPP) || (Extra Class)",
      "Decidability 02 : Decidable and Undecidable Problems & Languages",
      "Decidability 01 : Definitions",
      "Turing Machine Recursively Enumerable 03 : Turing Machine (Part- 03) || (NO DPP)",
      "Turing Machine Recursively Enumerable 02 : Turing Machine (Part- 02)",
      "Turing Machine Recursively Enumerable 01 : Turing Machine (Part- 01)",
      "Push Down Automata 08 : Context Free Languages || Closure Properties-2 & Revision on CFLs || (NO DPP)",
      "Push Down Automata 07 : Context Free Languages || Closure Properties",
      "Push Down Automata 06 : Context Free Languages || CFLs & DCFLs",
      "Push Down Automata 05 : Context Free Languages || PDA - 03 || (NO DPP)",
      "Push Down Automata 04 : Context Free Languages || PDA - 02 || (EXTRA CLASS)",
      "Push Down Automata 03 : Context Free Languages || PDA - 01 || (EXTRA CLASS)",
      "Push Down Automata 02 : Context Free Languages || CFG",
      "Push Down Automata 01 : Context Free Languages || Revision Of Regulars And Introduction To CFLs || (NO DPP)",
      "Finite Automata 23 : Closure Properties of Regular Languages-03 || (NO DPP)",
      "Finite Automata 22 : Closure Properties of Regular Languages-02",
      "Finite Automata 21 : Closure Properties of Regular Languages- 01",
      "Finite Automata 20 : Regular Language Identification- 02 || (EXTRA CLASS) || (Rescheduled @01:00 PM)",
      "Finite Automata 19 : Regular Language Identification-01",
      "Finite Automata 18 : Regular Grammars-02 & Pumping Lemma-03 || (NO DPP)",
      "Finite Automata 17 : Regular Grammars-01 & Pumping Lemma-02",
      "Finite Automata 16 : FA with Output- 02 & Pumping Lemma- 01 || (NO DPP)",
      "Finite Automata 15 : FA with Output-01",
      "Finite Automata 14 : Practice on Regular Expressions and FA || (Extra Class) || (NO DPP)",
      "Finite Automata 13 : Conversions in FA  || (NO DPP)",
      "Finite Automata 12 : Regular Languages : Practice on DFA and NFA || (NO DPP)",
      "Finite Automata 11 : Regular Languages || NFA with Epsilon Moves",
      "Finite Automata 10 : Regular Languages : DFA- 05 || (NO DPP)",
      "Finite Automata 09 : Regular Languages : DFA- 04 || (NO DPP)",
      "Finite Automata 08 : Regular Languages : NFA",
      "Finite Automata 07 : Regular Languages : DFA-03",
      "Finite Automata 06 : Regular Languages : DFA-02",
      "Finite Automata 05 : Regular Languages : DFA-01",
      "Finite Automata 04 : Practice on Regular Expression || (NO DPP)",
      "Finite Automata 03 : Regular Expression (Part-02)",
      "Finite Automata 02 : Regular Expression (Part-01)",
      "Finite Automata 01 : Basics Of TOC",
    ],
  },
};

module.exports = renameJobs;
